#pragma once

enum IMAGENUM
{
	IMAGENUM_BOARD = 1,
	IMAGENUM_WHITESTONE,
	IMAGENUM_BLACKSTONE,
	IMAGENUM_UIBUTTON,
	IMAGENUM_MEMO,
	IMAGENUM_LOBBYBACKGROUND,
	IMAGENUM_CHATBOARD_LOBBY,
	IMAGENUM_CHATBOARD_INGAME,
};
